### ISSUE TITLE
Remove dependency of Term Vectors

### ISSUE THREAD

**Issue by dsmiley** [dbmdz/solr-ocrpayload-plugin#2]
Hello,

You have a really cool Solr plugin here!  I'm writing to suggest possible improvements.  

I noticed that this plugin is written to require term vectors.  TVs are rather expensive in Lucene, both in disk usage and overhead to fetch them.  And it's TermsEnum impl is O(N) (as your comments show you realize).  In some cases people use them when I don't think they are actually needed -- like I see here.  The main index postings can have offsets and payloads; you can write a highlighter-like thing that uses the information there instead of term vectors.  The UnifiedHighlighter (which I was involved in creating) does exactly this; you may find it interesting.

**Comment by jbaiter** [comment]
Thank you so much for the suggestions! I'll study the `UnifiedHighlighter` and see what I can do :-)

**Comment by jbaiter** [comment]
Wow, that was easier than expected and resulted in a *huge* reduction in index size:

**Before**:
```
Fields Index                 0.0GiB   0.0%
Norms (nvm)                  0.0GiB   0.0%
Norms (nvd)                  0.0GiB   0.0%
Term Vector Index            0.0GiB   0.0%
Field Data                   0.0GiB   0.0%
Fields Info                  0.0GiB   0.0%
Segment Info                 0.0GiB   0.0%
Term Index                   0.0GiB   0.1%
Frequencies                  0.0GiB   0.6%
Term Dictionary              0.1GiB   4.5%
Payloads                     0.5GiB  22.9%
Positions                    0.5GiB  24.0%
Term Vector Documents        1.0GiB  47.9%
==========================================
Total                        2.0GiB
```

**After**:
```
Fields Index                 0.0GiB   0.0%
Norms (nvm)                  0.0GiB   0.0%
Norms (nvd)                  0.0GiB   0.0%
Field Data                   0.0GiB   0.0%
Fields Info                  0.0GiB   0.0%
Segment Info                 0.0GiB   0.0%
Term Index                   0.0GiB   0.2%
Frequencies                  0.0GiB   1.2%
Term Dictionary              0.1GiB   8.6%
Payloads                     0.5GiB  43.9%
Positions                    0.5GiB  46.1%
==========================================
Total                        1.1GiB
```

On top of that, looking at `UnifiedHighlighter` I was finally able to get rid of the ugly reflection-based `FieldQueryAdapter`-approach to obtaining the query terms!

@dsmiley, If you're ever in Munich, ping me, I owe you a lot of beers :-)

**Comment by dsmiley** [comment]
Glad to be of help :-)  

I am curious what led you to use term vectors in the first place?  I want to discuss with the Lucene community on restricting what TVs are massively to just the terms in the doc-field; I think they can easily be overused to do things they aren't so good at.

**Comment by jbaiter** [comment]
Honestly, it was simply unfamiliarity with the Solr/Lucene APIs and internals.

I knew that I wanted to store the coordinates in the payloads, so I began grepping the documentation for mentions of payloads, which led me to https://lucene.apache.org/solr/guide/6_6/defining-fields.html, where I completely missed the `omitTermFreqAndPositions` entry and just saw the `termPayloads` option. This led me to believe that payloads required term vectors, and the rest followed from that.
